import type { Metadata } from "next";
import "./globals.scss";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "플랜줍줍",
  description: "Generated by create next app",
};

export type TOnClickProfileArea = () => void;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <main>
          <Suspense fallback={<div>Loading...</div>}>
            {children}
          </Suspense>
        </main>
        <Footer />
      </body>
    </html>
  );
}

/* eslint-disable */